name: cd

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    # This job will only run if the PR has been merged (and not closed without merging).
    if: "github.event.pull_request.merged == true && !contains(github.event.pull_request.head.message, 'skipci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - name: Get package version
        id: version
        run: echo "::set-output name=package_version::$(poetry version -s)"

      - name: Generate icon atlas and icon mapping
        id: generate-icon-meta
        run: echo "Generating icon atlas and icon mapping"

      - name: Commit sprite sheet to repo public folder
        id: commit-back
        run: echo "Committing generated icon atlas and icon mapping to repo"

      # - name: Create release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own.
      #   with:
      #     tag_name: ${{ steps.version.outputs.package_version }}
      #     release_name: ${{ github.event.pull_request.title }}
      #     body: ${{ github.event.pull_request.body }}
      #     draft: false
      #     prerelease: false
