name: cd

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    # This job will only run if the PR has been merged (and not closed without merging).
    if: "github.event.pull_request.merged == true && !contains(github.event.pull_request.head.message, 'skipci')"
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - name: Get package version
        id: version
        run: echo "::set-output name=package_version::$(poetry version -s)"

      - name: Install dependencies
        run: poetry install

      - name: Generate icon atlas and icon mapping
        id: generate-icon-meta
        run: poetry run python scripts/generate_icon_atlas_and_mapping.py

      - name: Commit sprite sheet to repo public folder
        id: commit-back
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "OPS: Generate icon atlas and icon mapping"
